name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install
        uses: ivanklee86/python_pipenv_action@master
        run: pipenv install --dev

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Run tests
        uses: ivanklee86/python_pipenv_action@master
        run: pipenv install --dev
        env:
          SLACK_CHANNEL: C5BMKV7EV
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      - name: Send results 2 slack
        uses: ./
        env:
          SLACK_CHANNEL: CKQ7C7KJN
          XUNIT_PATH: ./results.xml
          EXIT_CODE_FROM_REPORT: True
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}

  lint:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Runs pylint
        uses: ivanklee86/python_pipenv_action@master
        run: pipenv run pylint app

  mypy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Runs pylint
        uses: ivanklee86/python_pipenv_action@master
        run: pipenv run mypy app

  notify:
    runs-on: ubuntu-latest
    needs: [test, lint, mypy]
    steps:
      - name: Notify completion
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_USERNAME: Github
          SLACK_ICON: https://slack-files2.s3-us-west-2.amazonaws.com/avatars/2017-12-19/288981919427_f45f04edd92902a96859_512.png
          SLACK_COLOR: #3278BD
          SLACK_TITLE: CI pipeline completed
          SLACK_MESSAGE: ":rocket:"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
